openapi: 3.0.0
info:
  title: Devjobs App
  description: Devjobs App API
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: local server
  - url: https://devjobs-api-nu3z.onrender.com/api
    description: Web server
paths:
  /jobs:
    get:
      tags:
        - Jobs
      summary: Get all jobs
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
